Fix indentation in Debian post and pre scripts
There is several misindentation inside Debian post and pre
installation scripts. False indentation with space
as indent space should be 2 and indentation with tabs.

Adopt upstream commit 7cbb45d1d4b1a5e2d07b1c17c49a5ca797df8991
in Debian by conserving customizations in:
- debian/mariadb-server.postinst
- debian/mariadb-server.postrm
- debian/mariadb-server.preinst

diff --git a/debian/mariadb-server.postrm b/debian/mariadb-server.postrm
--- a/debian/mariadb-server.postrm
+++ b/debian/mariadb-server.postrm
@@ -21,25 +21,25 @@ fi
 # do it himself. No database directories should be removed while the server
 # is running! Another mariadbd in e.g. a different chroot is fine for us.
 stop_server() {
-    # Return immediately if there are no mysqld processes running
-    # as there is no point in trying to shutdown in that case.
-    if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
+  # Return immediately if there are no mysqld processes running
+  # as there is no point in trying to shutdown in that case.
+  if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
 
-    set +e
-    invoke-rc.d mariadb stop
-    invoke-rc.d mysql stop # Backwards compatibility
-    errno=$?
-    set -e
+  set +e
+  invoke-rc.d mariadb stop
+  invoke-rc.d mysql stop # Backwards compatibility
+  errno=$?
+  set -e
 
-    # systemctl could emit exit code 100=no init script (fresh install)
-    if [ "$errno" != 0 -a "$errno" != 100 ]; then
-      echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
-      echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
-      echo "Check if there is any server running with 'pgrep \"mysqld|mariadbd\"' and" 1>&2
-      echo "try to stop it yourself by issuing 'invoke-rc.d mariadb stop'." 1>&2
-      db_stop
-      exit 1
-    fi
+  # systemctl could emit exit code 100=no init script (fresh install)
+  if [ "$errno" != 0 -a "$errno" != 100 ]; then
+    echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+    echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
+    echo "Check if there is any server running with 'pgrep \"mysqld|mariadbd\"' and" 1>&2
+    echo "try to stop it yourself by issuing 'invoke-rc.d mariadb stop'." 1>&2
+    db_stop
+    exit 1
+  fi
 }
 
 
@@ -49,11 +49,11 @@ case "$1" in
       stop_server
       sleep 2
     fi
-  ;;
+    ;;
   *)
     echo "postrm called with unknown argument '$1'" 1>&2
     exit 1
-  ;;
+    ;;
 esac
 
 #
@@ -82,9 +82,9 @@ if [ "$1" = "purge" ] && [ -f "/var/lib/mysql/debian-__MARIADB_MAJOR_VER__.flag"
     if [ -d /var/lib/mysql ]
     then
       find /var/lib/mysql -mindepth 1 \
-           -not -path '*/lost+found/*'     -not -name 'lost+found' \
-           -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
-           -delete
+        -not -path '*/lost+found/*'     -not -name 'lost+found' \
+        -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
+        -delete
 
       # "|| true" still needed as rmdir still exits with non-zero if
       # /var/lib/mysql is a mount point
@@ -100,5 +100,5 @@ fi
 
 # Modified dh_systemd_start snippet that's not added automatically
 if [ -d /run/systemd/system ]; then
-	systemctl --system daemon-reload >/dev/null || true
+  systemctl --system daemon-reload >/dev/null || true
 fi
diff --git a/debian/mariadb-server.preinst b/debian/mariadb-server.preinst
--- a/debian/mariadb-server.preinst
+++ b/debian/mariadb-server.preinst
@@ -11,7 +11,7 @@
 
 # Just kill the invalid insserv.conf.d directory without fallback
 if [ -d "/etc/insserv.conf.d/mariadb/" ]; then
-    rm -rf "/etc/insserv.conf.d/mariadb/"
+  rm -rf "/etc/insserv.conf.d/mariadb/"
 fi
 
 if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
@@ -34,25 +34,25 @@ fi
 # do it himself. No database directories should be removed while the server
 # is running! Another mariadbd in e.g. a different chroot is fine for us.
 stop_server() {
-    # Return immediately if there are no mysqld processes running on a host
-    # (leave containerized processes with the same name in other namespaces)
-    # as there is no point in trying to shutdown in that case.
-    if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
+  # Return immediately if there are no mysqld processes running on a host
+  # (leave containerized processes with the same name in other namespaces)
+  # as there is no point in trying to shutdown in that case.
+  if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
 
-    set +e
-    invoke-rc.d mariadb stop
-    invoke-rc.d mysql stop # Backwards compatibility
-    errno=$?
-    set -e
+  set +e
+  invoke-rc.d mariadb stop
+  invoke-rc.d mysql stop # Backwards compatibility
+  errno=$?
+  set -e
 
-    # systemctl could emit exit code 100=no init script (fresh install)
-    if [ "$errno" != 0 -a "$errno" != 100 ]; then
-      echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
-      echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
-      echo "Stop it yourself and try again!" 1>&2
-      db_stop
-      exit 1
-    fi
+  # systemctl could emit exit code 100=no init script (fresh install)
+  if [ "$errno" != 0 -a "$errno" != 100 ]; then
+    echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+    echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
+    echo "Stop it yourself and try again!" 1>&2
+    db_stop
+    exit 1
+  fi
 }
 
 ################################ main() ##########################
@@ -120,7 +120,7 @@ then
   fi
 
   if dpkg --compare-versions "$found_version" '>>' "$max_upgradeable_version" \
-  && dpkg --compare-versions "$found_version" '<<' "10.0"
+    && dpkg --compare-versions "$found_version" '<<' "10.0"
   then
     downgrade_detected=true
   fi
@@ -179,8 +179,8 @@ fi
 
 # creating mysql group if he isn't already there
 if ! getent group mysql >/dev/null; then
- 	# Adding system group: mysql.
-	addgroup --system mysql >/dev/null
+  # Adding system group: mysql.
+  addgroup --system mysql >/dev/null
 fi
 
 # creating mysql user if he isn't already there
@@ -188,13 +188,13 @@ if ! getent passwd mysql >/dev/null; then
 	# Adding system user: mysql.
 	adduser \
 	  --system \
-          --disabled-login \
+    --disabled-login \
 	  --ingroup mysql \
 	  --no-create-home \
 	  --home /nonexistent \
 	  --gecos "MariaDB Server" \
 	  --shell /bin/false \
-	  mysql  >/dev/null 2>&1
+	  mysql >/dev/null 2>&1
 fi
 
 # end of NIS tolerance zone
@@ -213,7 +213,7 @@ done
 
 # creating mysql home directory
 if [ ! -d $mysql_datadir ] && [ ! -L $mysql_datadir ]; then
-	# Use mkdir option 'Z' to create with correct SELinux context.
+  # Use mkdir option 'Z' to create with correct SELinux context.
   mkdir -Z $mysql_datadir
 fi
 
