Salsa-CI: Re-enable upgrade tests for Buster to Sid
Upgrade tests from Stretch to Sid and Buster to Sid were previously
disabled due to Bug#993755. Re-enable upgrade tests from Buster now with
workaround applied in the step that enables Sid repositories.

Do not re-enable any Stretch upgrade tests - that is already
oldoldstable and *not* even the most outdated Debian LTS users should
attempt to jump from Stretch MariaDB 10.1 directly to Sid/Bookworm
MariaDB 10.6.

Also refactor the structure so that we have:

- Simple upgrade tests to ensure the newly built packages upgrade nicely
  replacing the previous packages.

- Complex upgrade tests to ensure the newly built packages upgrade
- nicely and that the distro release upgrade also works.

- Cross-vendor upgrade tests to ensure the newly built packages upgrade
  nicely replacing similar but not identical packages from another third
  party repositories.

- Review attempted use of as there is no init.d/mysql in MariaDB 10.5+
  anymore
  https://packages.debian.org/search?suite=bullseye&arch=any&mode=path&searchon=contents&keywords=%2Fetc%2Finit.d%2Fmysql

- Shorter and more clear naming of all stages

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -26,9 +26,9 @@ stages:
   - provisioning
   - build
   - test
-  - upgrade in Sid
-  - upgrade from Bullseye
-  - upgrade extras
+  - upgrade MariaDB
+  - upgrade MariaDB and distro
+  - upgrade MariaDB variant
   - test extras
   - publish # Stage referenced by Salsa-CI template aptly stanza, so must exist even though not used
 
@@ -78,11 +78,6 @@ packaging-fix-checks:
   except:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
-
-
-# build jobs often needs more than default GitLab timeout (1h)
-.build-package:
-  timeout: 3h
 
 build bullseye-backports:
   extends: .build-package
@@ -138,12 +133,37 @@ blhc:
   mysql --table -e "SELECT * FROM plugin;" mysql
   mysql --table -e "SHOW PLUGINS;" mysql
 
-.test-enable-sid-repos: &test-enable-sid-repos |
+.test-enable-sid-repos: &test-enable-sid-repos
   # Replace any old repos with just Sid
-  echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
+  - echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
   # Upgrade minimal stack first
+  - apt-get update
+  # Next step will fail on https://bugs.debian.org/993755
+  #   /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot
+  #     open shared object file: No such file or directory
+  #   dpkg: error processing package libc6:amd64 (--configure):
+  - apt-get install -y apt || true
+  # Apply workaround
+  - cd $(mktemp -d) # Use temp dir where apt can download and unpack files
+  - apt-get -y download libcrypt1
+  - dpkg-deb -x libcrypt1_*.deb .
+  - cp -ra lib/* /lib/
+  - cd - # Back to /builds/$USER/mariadb-server/debian/output
+  - find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
+  - apt-get -y --fix-broken install
+  # Complete upgrade of minimal stack
+  - apt-get install -y apt
+
+.test-enable-bullseye-backports-repos: &test-enable-bullseye-backports-repos |
+  # Enable bullseye-backports (assumes environment already Debian Bullseye)
+  echo 'deb http://deb.debian.org/debian bullseye-backports main' > /etc/apt/sources.list.d/bullseye-backports.list
+  # Increase default backports priority policy from '100' to '500' so it can actually be used
+  cat << EOF > /etc/apt/preferences.d/enable-backports-to-satisfy-dependencies
+  Package: *
+  Pin: release n=bullseye-*
+  Pin-Priority: 500
+  EOF
   apt-get update
-  apt-get install -y apt
 
 .test-enable-buster-backports-repos: &test-enable-buster-backports-repos |
   # Enable buster-backports (assumes environment already Debian Buster)
@@ -243,8 +263,8 @@ fresh install:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb-10.6 Sid upgrade:
-  stage: upgrade in Sid
+upgrade from mariadb-10.6 in Sid:
+  stage: upgrade MariaDB
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -264,10 +284,10 @@ mariadb-10.6 Sid upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb-10.5 Bullseye to mariadb-10.6 upgrade:
-  stage: upgrade from Bullseye
+upgrade from mariadb-10.5 with Bullseye backports:
+  stage: upgrade MariaDB variant
   needs:
-    - job: build
+    - job: build bullseye-backports
   image: debian:bullseye
   artifacts:
     when: always
@@ -276,13 +296,13 @@ mariadb-10.5 Bullseye to mariadb-10.6 upgrade:
       - ${WORKING_DIR}/debug
   script:
     - *test-prepare-container
-    # Install everything MariaDB currently in Debian Bullseye
+    # Install everything MariaDB currently in Debian Buster
     - apt-get install -y 'default-mysql*' 'mariadb-*' 'libmariadb*'
-    # Verify installation of MariaDB from Bullseye
+    # Verify installation of MariaDB from Buster
     - *test-verify-initial
-    - *test-enable-sid-repos
+    - *test-enable-bullseye-backports-repos
     - *test-install
-    - service mariadb status
+    - service mariadb status # There is no init.d/mysql in MariaDB 10.5+
     - *test-verify-final
   variables:
     GIT_STRATEGY: none
@@ -290,8 +310,8 @@ mariadb-10.5 Bullseye to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb-10.3 to mariadb-10.6 upgrade in Buster:
-  stage: upgrade extras
+upgrade from mariadb-10.3 with Buster backports:
+  stage: upgrade MariaDB variant
   needs:
     - job: build buster-backports
   image: debian:buster
@@ -308,7 +328,63 @@ mariadb-10.3 to mariadb-10.6 upgrade in Buster:
     - *test-verify-initial
     - *test-enable-buster-backports-repos
     - *test-install
+    # mariadb-10.3 in Buster ships a /etc/init.d/mysql so it should continue to work
     - service mysql status
+    - service mariadb status
+    - *test-verify-final
+  variables:
+    GIT_STRATEGY: none
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
+
+upgrade from mariadb-10.5 and Bullseye:
+  stage: upgrade MariaDB and distro
+  needs:
+    - job: build
+  image: debian:bullseye
+  artifacts:
+    when: always
+    name: "$CI_BUILD_NAME"
+    paths:
+      - ${WORKING_DIR}/debug
+  script:
+    - *test-prepare-container
+    # Install everything MariaDB currently in Debian Bullseye
+    - apt-get install -y 'default-mysql*' 'mariadb-*' 'libmariadb*'
+    # Verify installation of MariaDB from Bullseye
+    - *test-verify-initial
+    - *test-enable-sid-repos
+    - *test-install
+    - service mariadb status # There is no init.d/mysql in MariaDB 10.5+
+    - *test-verify-final
+  variables:
+    GIT_STRATEGY: none
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
+
+upgrade from mariadb-10.3 and Buster:
+  stage: upgrade MariaDB and distro
+  needs:
+    - job: build
+  image: debian:buster
+  artifacts:
+    when: always
+    name: "$CI_BUILD_NAME"
+    paths:
+      - ${WORKING_DIR}/debug
+  script:
+    - *test-prepare-container
+    # Install everything MariaDB currently in Debian Buster
+    - apt-get install -y 'default-mysql*' 'mariadb-*' 'libmariadb*'
+    # Verify installation of MariaDB from Buster
+    - *test-verify-initial
+    - *test-enable-sid-repos
+    - *test-install
+    # mariadb-10.3 in Buster ships a /etc/init.d/mysql so it should continue to work
+    - service mysql status
+    - service mariadb status
     - *test-verify-final
   variables:
     GIT_STRATEGY: none
@@ -421,7 +497,7 @@ build mariadbclient consumer Python-MySQLdb:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
 libmysql* to libmariadb* upgrade:
-  stage: upgrade in Sid
+  stage: upgrade MariaDB
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -454,7 +530,7 @@ libmysql* to libmariadb* upgrade:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
 default-libmysqlclient-dev Sid upgrade:
-  stage: upgrade in Sid
+  stage: upgrade MariaDB
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -473,8 +549,8 @@ default-libmysqlclient-dev Sid upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-default-libmysqlclient-dev Bullseye upgrade:
-  stage: upgrade from Bullseye
+upgrade default-libmysqlclient-dev and Bullseye:
+  stage: upgrade MariaDB and distro
   needs:
     - job: build
   image: debian:bullseye
@@ -494,8 +570,50 @@ default-libmysqlclient-dev Bullseye upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-default-libmysqlclient-dev upgrade in Buster:
-  stage: upgrade extras
+upgrade default-libmysqlclient-dev and Buster:
+  stage: upgrade MariaDB and distro
+  needs:
+    - job: build
+  image: debian:buster
+  artifacts:
+    when: always
+    name: "$CI_BUILD_NAME"
+    paths:
+      - ${WORKING_DIR}/debug
+  script:
+    - *test-prepare-container
+    - apt-get install -y pkg-config default-libmysqlclient-dev
+    - pkg-config --list-all
+    - *test-enable-sid-repos
+    - *test-install-all-libs
+    - *test-verify-libs
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
+
+upgrade default-libmysqlclient-dev with Bullseye backports:
+  stage: upgrade MariaDB
+  needs:
+    - job: build bullseye-backports
+  image: debian:bullseye
+  artifacts:
+    when: always
+    name: "$CI_BUILD_NAME"
+    paths:
+      - ${WORKING_DIR}/debug
+  script:
+    - *test-prepare-container
+    - apt-get install -y pkg-config default-libmysqlclient-dev
+    - pkg-config --list-all
+    - *test-enable-bullseye-backports-repos
+    - *test-install-all-libs
+    - *test-verify-libs
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
+
+upgrade default-libmysqlclient-dev with Buster backports:
+  stage: upgrade MariaDB
   needs:
     - job: build buster-backports
   image: debian:buster
@@ -517,8 +635,8 @@ default-libmysqlclient-dev upgrade in Buster:
 
 # Upgrading from MySQL 8.0 with datadir in place is not possible. Users need to do a data dump.
 # The Debian maintainer scripts detect this situation and simply moves old datadir aside and start fresh.
-mysql-8.0 Sid to mariadb-10.6 upgrade:
-  stage: upgrade in Sid
+upgrade from mysql-8.0 in Sid:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:sid
@@ -552,8 +670,8 @@ mysql-8.0 Sid to mariadb-10.6 upgrade:
 
 # Upgrading from MySQL 8.0 with datadir in place is not possible. Users need to do a data dump.
 # The Debian maintainer scripts detect this situation and simply moves old datadir aside and start fresh.
-mysql-8.0 Focal to mariadb-10.6 upgrade in Buster:
-  stage: upgrade extras
+upgrade from mysql-8.0 from Ubuntu 20.04 with Buster backports:
+  stage: upgrade MariaDB variant
   needs:
     - job: build buster-backports
   image: debian:buster
@@ -585,8 +703,8 @@ mysql-8.0 Focal to mariadb-10.6 upgrade in Buster:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb.org-10.6 to mariadb-10.6 upgrade:
-  stage: upgrade extras
+upgrade from mariadb.org-10.6:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -620,8 +738,8 @@ mariadb.org-10.6 to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb.org-10.5 to mariadb-10.6 upgrade:
-  stage: upgrade extras
+upgrade from mariadb.org-10.5:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -650,8 +768,8 @@ mariadb.org-10.5 to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb.org-10.4 to mariadb-10.6 upgrade:
-  stage: upgrade extras
+upgrade from mariadb.org-10.4:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -683,8 +801,8 @@ mariadb.org-10.4 to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb.org-10.3 to mariadb-10.6 upgrade:
-  stage: upgrade extras
+upgrade from mariadb.org-10.3:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -714,8 +832,8 @@ mariadb.org-10.3 to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mariadb.org-10.2 to mariadb-10.6 upgrade:
-  stage: upgrade extras
+upgrade from mariadb.org-10.2:
+  stage: upgrade MariaDB variant
   needs:
     - job: build
   image: debian:${RELEASE}
@@ -753,8 +871,8 @@ mariadb.org-10.2 to mariadb-10.6 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mysql.com-5.7 to mariadb-10.6 upgrade in Buster:
-  stage: upgrade extras
+upgrade from mysql.com-5.7 with Buster backports:
+  stage: upgrade MariaDB variant
   needs:
     - job: build buster-backports
   image: debian:buster
@@ -784,8 +902,8 @@ mysql.com-5.7 to mariadb-10.6 upgrade in Buster:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-percona-xtradb-5.7 to mariadb-10.6 upgrade in Buster:
-  stage: upgrade extras
+upgrade from percona-xtradb-5.7 with Buster backports:
+  stage: upgrade MariaDB variant
   needs:
     - job: build buster-backports
   image: debian:buster
