Salsa-CI: Clean up after sid/testing has had mariadb-10.3 removed now
Also add testing for MySQL 5.7 upgrades since Debian Sid contains both
MySQL 8.0 and MySQL 5.7.

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -1,10 +1,10 @@
 ---
-# Inlude Salsa-CI as a base
+# Include Salsa-CI as a base
 include:
   - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
   - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml
 
-# Overridfe Salsa-CI with MariaDB specific variations
+# Override Salsa-CI with MariaDB specific variations
 variables:
   DEB_BUILD_OPTIONS: "nocheck noautodbgsym"
   RELEASE: sid
@@ -26,9 +26,10 @@ gnitpick:
   stage: provisioning
   image: debian:sid
   script: |
-    # Actual Gnitpick part
-    apt-get update -qq && apt-get -qq install --no-install-recommends --yes ca-certificates curl python3-minimal git # Bare minimal (<4MB) for apt-key and gnitpick to work
+    # Bare minimal (<4MB) for apt-key and gnitpick to work
+    apt-get update -qq && apt-get -qq install --no-install-recommends --yes ca-certificates curl python3-minimal git
     curl -sS https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py -o /usr/bin/gnitpick; chmod +x /usr/bin/gnitpick
+    # Actual Gnitpick part
     gnitpick --target-repository https://salsa.debian.org/mariadb-team/mariadb-10.5.git
   except:
     variables:
@@ -39,7 +40,6 @@ build buster-backports:
   variables:
     RELEASE: buster-backports
 
-# Temporairly disable until https://salsa.debian.org/salsa-ci-team/pipeline/-/issues/175 is fixed
 build stretch-backports:
   extends: .build-package
   variables:
@@ -87,9 +87,7 @@ blhc:
   echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
   # Upgrade minimal stack first
   apt-get update
-  # Due to Bug#972552, libnss-nis fails with exit code 100, so install it here
-  # as a separate step that is safe to ignore
-  apt-get install -y apt libnss-nis || true
+  apt-get install -y apt
 
 .test-install: &test-install |
   # Install MariaDB built in this commit
@@ -118,6 +116,7 @@ blhc:
   - pkg-config --cflags --libs mariadb
   - apt-get install -y --no-install-recommends g++
   - |
+    # Build a test binary that depends on libmysqlclient
     cat > b933063.cpp <<EOF
     #include <iostream>
     #include <mysql/mysql.h>
@@ -211,8 +210,8 @@ mariadb-10.3 Buster to mariadb-10.5 upgrade:
       - ${WORKING_DIR}/debug
   script:
     - *test-prepare-container
-    # Install almost everything currently in Debian Buster
-    - apt-get install -y 'default-mysql*' 'mariadb-*' libmariadb3 'libmariadb-*' 'libmariadbd*' 'libmariadbclient-*'
+    # Install everything MariaDB currently in Debian Buster
+    - apt-get install -y 'default-mysql*' 'mariadb-*' 'libmariadb*'
     # Verify installation of MariaDB from Buster
     - *test-verify-initial
     - *test-enable-sid-repos
@@ -238,7 +237,8 @@ mariadb-10.1 Stretch to mariadb-10.5 upgrade:
       - ${WORKING_DIR}/debug
   script:
     - *test-prepare-container
-    # Install almost everything currently in Debian Stretch
+    # Install almost everything currently in Debian Stretch,
+    # omitting libmariadbclient-dev-compat as it would conflict
     - apt-get install -y 'default-mysql*' 'mariadb-*' 'libmariadbd*' 'libmariadbclient*'
     # Verify installation of MariaDB from Buster
     - *test-verify-initial
@@ -293,8 +293,8 @@ test basic features:
       mariadb -e "SELECT COUNT(*) FROM db.v_temptable"
       mariadb -e "CALL db.p()"
       mariadb -e "SELECT db.f()"
-    # Test TLS connections
     - |
+      # Test TLS connections
       dpkg -l | grep -i -e tls -e ssl
       # Create user for TCP connection, must have password
       mariadb -e "SET PASSWORD FOR 'mysql'@'localhost' = PASSWORD('asdf234');"
@@ -494,7 +494,9 @@ mysql-8.0 Sid to mariadb-10.5 upgrade:
       - ${WORKING_DIR}/debug
   script:
     - *test-prepare-container
-    - apt-get install -y mysql-server
+    # First install often fail due to bug in mysql-8.0
+    - apt-get install -y mysql-server 'libmysqlc*' || true
+    - sleep 10 && apt-get install -f
     - *test-verify-initial
     - *test-install
     - service mysql status
@@ -507,6 +509,31 @@ mysql-8.0 Sid to mariadb-10.5 upgrade:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
   # Installation often fails (not a MariaDB reason), so do not require this test to pass
   allow_failure: true
+
+mysql-5.7 Sid to mariadb-10.5 upgrade:
+  stage: upgrade in Sid
+  needs:
+    - job: build
+      artifacts: true
+  image: debian:sid
+  artifacts:
+    when: always
+    name: "$CI_BUILD_NAME"
+    paths:
+      - ${WORKING_DIR}/debug
+  script:
+    - *test-prepare-container
+    - apt-get install -y mysql-server-5.7 'libmysqlc*'
+    - *test-verify-initial
+    - *test-install
+    - service mysql status
+    - sleep 5 # Give the mysql_upgrade a bit of time to complete before querying the server
+    - *test-verify-final
+  variables:
+    GIT_STRATEGY: none
+  except:
+    variables:
+      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
 # Upgrading from MySQL 8.0 with datadir in place is not possible. Users need to do a data dump.
 # The Debian maintainer scripts detect this situation and simply moves old datadir aside and start fresh.
@@ -528,7 +555,9 @@ mysql-8.0 Focal to mariadb-10.5 upgrade:
     - apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com:443 871920D1991BC93C 3B4FE6ACC0B21F32
     - echo 'deb http://archive.ubuntu.com/ubuntu/ focal main restricted' > /etc/apt/sources.list.d/ubuntu.list
     - apt-get update
-    - apt-get install -y mysql-server 'mysql*' 'libmysqlc*'
+    # First install often fail due to bug in mysql-8.0
+    - apt-get install -y mysql-server 'libmysqlc*' || true
+    - sleep 10 && apt-get install -f
     - *test-verify-initial
     # Enable backports to make galera-4 available
     - echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list && apt-get update
@@ -562,7 +591,7 @@ mysql-5.7 Bionic to mariadb-10.5 upgrade:
     - apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com:443 871920D1991BC93C 3B4FE6ACC0B21F32
     - echo 'deb http://archive.ubuntu.com/ubuntu/ bionic main restricted' > /etc/apt/sources.list.d/ubuntu.list
     - apt-get update
-    - apt-get install -y mysql-server 'mysql*' 'libmysqlc*'
+    - apt-get install -y 'mysql*' 'libmysqlc*'
     - *test-verify-initial
     # Enable backports to make libzstd1, rocksdb-tools
     - echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list.d/backports.list
@@ -597,9 +626,8 @@ mariadb.org-10.5 to mariadb-10.5 upgrade:
     - curl -sS https://mariadb.org/mariadb_release_signing_key.asc -o /etc/apt/trusted.gpg.d/mariadb.asc
     - echo 'deb http://mirror.one.com/mariadb/repo/10.5/debian sid main' > /etc/apt/sources.list.d/mariadb.list
     - apt-get update
-    # Plugins wildcard omitted as mariadb-plugin-tokudb for 10.3 in Debian Sid would mess it up
-    # Also libmariadbclient-dev in Debian Sid would end up depending on libmariadb-dev from 10.3
-    - apt-get install -y mariadb-server-10.5 libmariadb3 'libmariadb-*' 'libmariadbd*'
+    # Package libmariadbclient-dev from mariadb.org conficts with libmariadb-dev in Sid, so cannot use wildcard that would include it
+    - apt-get install -y 'mariadb*' libmariadb3 'libmariadb-*' 'libmariadbd*'
     - *test-verify-initial
     # Install MariaDB built in this commit
     # Force downgrades so our version installs on top of upstream revision, e.g. 1:10.5.5-1 vs 1:10.5.5+mariadb~sid
@@ -632,10 +660,7 @@ mariadb.org-10.4 to mariadb-10.5 upgrade:
     - curl -sS https://mariadb.org/mariadb_release_signing_key.asc -o /etc/apt/trusted.gpg.d/mariadb.asc
     - echo 'deb http://mirror.one.com/mariadb/repo/10.4/debian sid main' > /etc/apt/sources.list.d/mariadb.list
     - apt-get update
-    # Plugins wildcard omitted as mariadb-plugin-tokudb for 10.3 in Debian Sid would mess it up
-    # Also libmariadbclient-dev in Debian Sid would end up depending on libmariadb-dev from 10.3
-    # and libmariadb-dev-dbgsym in Debian Sid on libmariadb-dev from 10.4
-    - apt-get install -y mariadb-server-10.4 libmariadb3 libmariadb-dev libmariadb-dev-compat
+    - apt-get install -y mariadb-server-10.4
     # MariaDB.org version of 10.4 and early 10.5 do not install an init file, so
     # it must be installed here manually
     - cp /usr/share/mysql/mysql.init /etc/init.d/mysql; chmod +x /etc/init.d/mysql; service mysql start; sleep 5
@@ -668,8 +693,7 @@ mariadb.org-10.3 to mariadb-10.5 upgrade:
     - curl -sS https://mariadb.org/mariadb_release_signing_key.asc -o /etc/apt/trusted.gpg.d/mariadb.asc
     - echo 'deb http://mirror.one.com/mariadb/repo/10.3/debian sid main' > /etc/apt/sources.list.d/mariadb.list
     - apt-get update
-    # See mariadb.org-10.4 comments
-    - apt-get install -y mariadb-server-10.3 libmariadb3 libmariadb-dev libmariadb-dev-compat
+    - apt-get install -y mariadb-server-10.3
     # Verify initial state before upgrade
     - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
     - service mysql status
@@ -705,8 +729,7 @@ mariadb.org-10.2 to mariadb-10.5 upgrade:
     - curl -sS https://mariadb.org/mariadb_release_signing_key.asc -o /etc/apt/trusted.gpg.d/mariadb.asc
     - echo 'deb http://mirror.one.com/mariadb/repo/10.2/debian sid main' > /etc/apt/sources.list.d/mariadb.list
     - apt-get update
-    # See mariadb.org-10.4 comments
-    - apt-get install -y mariadb-server-10.2 libmariadb3 libmariadb-dev libmariadb-dev-compat
+    - apt-get install -y mariadb-server-10.2
     # Verify initial state before upgrade
     - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
     - service mysql status
@@ -725,7 +748,7 @@ mariadb.org-10.2 to mariadb-10.5 upgrade:
     variables:
       - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
 
-mysql.com-5.7 to mariadb-10.5 upgrade (MDEV-22678):
+mysql.com-5.7 to mariadb-10.5 upgrade:
   stage: upgrade extras
   needs:
     - job: build buster-backports
@@ -743,7 +766,7 @@ mysql.com-5.7 to mariadb-10.5 upgrade (MDEV-22678):
       apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com:443 8C718D3B5072E1F5
       echo 'deb https://repo.mysql.com/apt/debian/ buster mysql-5.7' > /etc/apt/sources.list.d/mysql.list
       apt-get update
-      apt-get install -y mysql-server 'mysql*' 'libmysqlc*'
+      apt-get install -y 'mysql*' 'libmysqlc*'
     - *test-verify-initial
     # Enable backports to make galera-4 available
     - echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list.d/backports.list && apt-get update
